attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  day_hour:
    '0.0': 0
    '1.0': 1
    '10.0': 2
    '11.0': 3
    '12.0': 4
    '13.0': 5
    '14.0': 6
    '15.0': 7
    '16.0': 8
    '17.0': 9
    '18.0': 10
    '19.0': 11
    '2.0': 12
    '20.0': 13
    '21.0': 14
    '22.0': 15
    '23.0': 16
    '3.0': 17
    '4.0': 18
    '5.0': 19
    '6.0': 20
    '7.0': 21
    '8.0': 22
    '9.0': 23
  day_of_week:
    '0': 0
    '1': 1
    '2': 2
    '3': 3
    '4': 4
    '5': 5
    '6': 6
  month:
    '1': 0
    '10': 1
    '11': 2
    '12': 3
    '2': 4
    '3': 5
    '4': 6
    '5': 7
    '6': 8
    '7': 9
    '8': 10
    '9': 11
embedding_paddings: []
embedding_sizes:
  day_hour: !!python/tuple
  - 24
  - 9
  day_of_week: !!python/tuple
  - 7
  - 5
  month: !!python/tuple
  - 12
  - 6
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.04323298059106412
log_gradient_flow: false
log_interval: 10
log_val_interval: 10
lstm_layers: 1
max_encoder_length: 36
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    v3AA8u1xVkA=
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    QL368QiEZUA=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- capacity
- lat
- long
- tilt
- orientation
- encoder_length
- normalize_generation_center
- normalize_generation_scale
time_varying_categoricals_decoder:
- month
- day_of_week
- day_hour
time_varying_categoricals_encoder:
- month
- day_of_week
- day_hour
time_varying_reals_decoder:
- time_idx
- dlwrf
- dswrf
- duvrs
- hcc
- lcc
- mcc
- sde
- sr
- t2m
- tcc
- u10
- u100
- v10
- v100
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- dlwrf
- dswrf
- duvrs
- hcc
- lcc
- mcc
- sde
- sr
- t2m
- tcc
- u10
- u100
- v10
- v100
- relative_time_idx
- normalize_generation
weight_decay: 0.0
x_categoricals:
- month
- day_of_week
- day_hour
x_reals:
- capacity
- lat
- long
- tilt
- orientation
- encoder_length
- normalize_generation_center
- normalize_generation_scale
- time_idx
- dlwrf
- dswrf
- duvrs
- hcc
- lcc
- mcc
- sde
- sr
- t2m
- tcc
- u10
- u100
- v10
- v100
- relative_time_idx
- normalize_generation
